### ISSUE TITLE
Can't connect to Home Asisstant when running from WebApplication host

### ISSUE THREAD

**Issue by luizbon** [net-daemon/netdaemon#1075]
## The problem

I'm following the docs on how to serve a web app.
After following the steps, I can run the app locally, and everything works as expected, but when I deploy it to my server, the WebSocket connection fails.

When I revert the code back to the generic Host, it works as expected.

## Environment

- NetDaemon release with the issue: 24.8.0
- Last working NetDaemon release (if known): 
- Operating environment (Home assistant Add-on/Docker/Dev setup): Add-on
- Link to integration documentation on our website: https://netdaemon.xyz/docs/user/tutorials/webhost/

## Link to or paste code that causes the issue

This is my Program.cs file
```c#
try
{
    var builder = WebApplication.CreateBuilder(args);

    builder.WebHost.ConfigureKestrel(options =>
    {
        options.ListenAnyIP(10000);
    });
    
    builder
        .Host
        .UseNetDaemonAppSettings()
        .UseNetDaemonDefaultLogging()
        .UseNetDaemonRuntime()
        .UseNetDaemonTextToSpeech()
        .UseNetDaemonMqttEntityManagement()
        .ConfigureServices((_, services) =>
        {
            services.AddAppsFromAssembly(Assembly.GetExecutingAssembly())
                .AddNetDaemonStateManager()
                .AddNetDaemonScheduler();
        });
        
    builder.Services.AddRazorComponents()
        .AddInteractiveServerComponents();
    
    var app = builder.Build();
    
    app.UseStaticFiles();
    app.UseAntiforgery();
    
    app.MapRazorComponents<App>()
        .AddInteractiveServerRenderMode();

    await app.RunAsync();
}
catch (Exception e)
{
    Console.WriteLine($"Failed to start host... {e}");
    throw;
}
```

## Traceback/Error logs

```txt
[19:38:31 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Starting NetDaemon runtime version custom_compiled.
[19:38:31 DBG] NetDaemon.Client.IHomeAssistantClient: Connecting to Home Assistant websocket on ws://192.168.1.223:8123/core/websocket
[19:38:31 DBG] NetDaemon.Client.IHomeAssistantClient: Error connecting to Home Assistant
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '404' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
[19:38:31 ERR] NetDaemon.Client.IHomeAssistantRunner: Error running HassClient
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '404' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
   at NetDaemon.Client.Internal.HomeAssistantClient.ConnectAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, CancellationToken cancelToken)
   at NetDaemon.Client.Internal.HomeAssistantRunner.InternalRunAsync(String host, Int32 port, Boolean ssl, String token, String websocketPath, TimeSpan timeout, CancellationToken cancelToken)
[19:38:31 INF] NetDaemon.Runtime.Internal.NetDaemonRuntime: Home Assistant disconnected due to unknown error, set loglevel to debug to view details, connect retry in 30 seconds
[19:38:31 INF] NetDaemon.Client.IHomeAssistantRunner: Client disconnected, retrying in 30 seconds...
```

## Additional information
I can publish the code as <Project Sdk="Microsoft.NET.Sdk.Web"> without problems, the issue is specific to the WebApplication hosting.

**Comment by luizbon** [comment]
After adding the source code to debug I have found the root cause.

The WebsocketPath was wrong, pointing to `core/websocket`. Adding `api/websocket` to the appsettings.json file fixed the issue.

```
"HomeAssistant": {
        "Host": "192.168.1.223",
        "Port": 8123,
        "Ssl": false,
        "Token": "...",
        "WebsocketPath": "api/websocket"
    }
```

Although, I'm not sure why the system was resolving `core/websocket`.

**Comment by helto4real** [comment]
> After adding the source code to debug I have found the root cause.
> 
> The WebsocketPath was wrong, pointing to `core/websocket`. Adding `api/websocket` to the appsettings.json file fixed the issue.
> 
> ```
> "HomeAssistant": {
>         "Host": "192.168.1.223",
>         "Port": 8123,
>         "Ssl": false,
>         "Token": "...",
>         "WebsocketPath": "api/websocket"
>     }
> ```
> 
> Although, I'm not sure why the system was resolving `core/websocket`.

Glad to hear. Thank you. It checks if it is in a add-on maybe your host was named the same. Glad it turned out good.
