### ISSUE TITLE
Exception with Code generator when an attribute name has no alfanumeric characters

### ISSUE THREAD

**Issue by Sascha-L** [net-daemon/netdaemon#1166]
Hi,

I'm playing around with your NetDaemon integration and tried your sample project template. Everything worked fine and also the code generation worked fine. Since yesterday the code generation is throwing an exception. The only changes I made where in Home Assistant (new automations, new devices, new helpers, etc.), so it might be a problem with a device or an entity.

## The problem
Exception after calling **dotnet tool run nd-codegen**  or  **nd-codegen**

## Environment
- NetDaemon release with the issue: latest
- Last working NetDaemon release (if known): latest
- Operating environment (Home assistant Add-on/Docker/Dev setup): latest

## Link to or paste code that causes the issue

```c#
**dotnet tool run nd-codegen**  or  **nd-codegen**
```

## Traceback/Error logs
```txt
nd-codegen
Codegen version: 24.35.1.0
Connecting to Home Assistant at 192.168.xxx.xxx:xxxx
nd-codegen : Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
In Zeile:1 Zeichen:1
+ nd-codegen
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...s of the array.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at NetDaemon.HassModel.CodeGenerator.Extensions.StringExtensions.ToValidCSharpIdentifier(String name) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/StringExtensions.cs:line 21
   at NetDaemon.HassModel.CodeGenerator.Extensions.StringExtensions.ToValidCSharpPascalCase(String name) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Extensions/StringExtensions.cs:line 11
   at NetDaemon.HassModel.CodeGenerator.AttributeMetaDataGenerator.<>c.<GetMetaDataFromEntityStates>b__0_2(IGrouping`2 group) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/AttributeMetaDataGenerator.cs:line 17
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at NetDaemon.HassModel.CodeGenerator.EntityMetaDataGenerator.mapEntityDomainMetadata(IGrouping`2 domainGroup) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataGenerator.cs:line 22
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at NetDaemon.HassModel.CodeGenerator.EntityMetaDataGenerator.GetEntityDomainMetaData(IReadOnlyCollection`1 entityStates) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/MetaData/EntityMetaData/EntityMetaDataGenerator.cs:line 16
   at NetDaemon.HassModel.CodeGenerator.Controller.RunAsync() in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Controller.cs:line 25
   at Program.<Main>$(String[] args) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs:line 24
   at Program.<Main>(String[] args)
```

**Comment by Sascha-L** [comment]
I downloaded your source code and debugged it.

It is happening here:
`public static string ToValidCSharpIdentifier(this string name)
    {
        Debug.WriteLine("Name: " + name);
        name = name.Replace(".", "_", StringComparison.InvariantCulture);

        name = Regex.Replace(name, "[^a-zA-Z0-9_]+", "", RegexOptions.Compiled);

        if (char.IsAsciiDigit(name[0]))
            name = "_" + name;

        return name;
    }`

If name is empty at the end, of course name[0] will throw an exception. So sometimes there might be entities with names only containing characters which are removed in this method. 

The exception should be catched and those entites should be skipped or getting random GUIDs as name?

In my case it is happening because of the iCloud3 integration which is using hyphens as dividing line:
![icloud3](https://github.com/user-attachments/assets/6174d74a-7972-4a18-b55f-59f5a6c8fd1d)

I will also contact the developers of iCloud3 that they should remove those dividing lines.

**Comment by helto4real** [comment]
@Sascha-L sorry for not noticing this before. Can you join our Discord server and discuss the error there please. https://discord.gg/K3xwfcX
@FrankBakkerNl (for your information)

**Comment by FrankBakkerNl** [comment]
Nice that you did the extra analysis and also got it fixed on the HA integration side. Now we also have the fix in ND not to crash codegen in this case
