### ISSUE TITLE
CodeGenerator cannot deserialize JSON selector and throws exception

### ISSUE THREAD

**Issue by rcjkierkels** [net-daemon/netdaemon#700]
## The problem
Since I updated to the latest version of HA I get the following error with the CodeGenerator. The issue seems to be the set_default_level service in HA (but probably there are more). At line 100 of [JsonExtensions](https://github.com/net-daemon/netdaemon/blob/36343964af75b23254a3deb8e0501757177e7139/src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/JsonExtensions.cs) it tries to deserialize the options into an SelectSelector object, but the options are not strings but objects.

This is what is tries to deserialize into a SelectSelector. But as you can see the options are objects, not strings.
```
ValueKind = Object : "{"options":[{"label":"Debug","value":"debug"},{"label":"Info","value":"info"},{"label":"Warning","value":"warning"},{"label":"Error","value":"error"},{"label":"Fatal","value":"fatal"},{"label":"Critical","value":"critical"}]}"
```

This results in an exception of this kind:

```
System.Text.Json.JsonException: The JSON value could not be converted to System.Collections.Generic.List`1[System.String]. Path: $.options[0] | LineNumber: 0 | BytePositionInLine: 13.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.<ToServicesResult>g__getSelector|1_2(String selectorName, JsonElement element, <>c__DisplayClass1_0& ) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Model\JsonExtensions.cs:line 100
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.<ToServicesResult>g__getField|1_3(String fieldName, JsonElement element, <>c__DisplayClass1_0& ) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Model\JsonExtensions.cs:line 151
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.<ToServicesResult>g__getServiceFields|1_1(String service, JsonElement element, <>c__DisplayClass1_0& ) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Model\JsonExtensions.cs:line 62
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.<ToServicesResult>g__getServices|1_0(JsonElement element, <>c__DisplayClass1_0& ) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Model\JsonExtensions.cs:line 40
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.ToServicesResult(JsonElement element) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Model\JsonExtensions.cs:line 27
   at Program.<<Main>$>g__GetHaData|0_1(HomeAssistantSettings homeAssistantSettings) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Program.cs:line 91
   at Program.<<Main>$>g__GetHaData|0_1(HomeAssistantSettings homeAssistantSettings) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Program.cs:line 95
   at Program.<Main>$(String[] args) in C:\Projects\netdaemon-source\src\HassModel\NetDaemon.HassModel.CodeGenerator\Program.cs:line 37
```

## How to reproduce
Update HA to the latest version, also update all netdeamon packages or use the dev-branch of this repository. Then run the CodeGenerator project and the exception is thrown.

## System Health

version | core-2022.4.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.103-v8
arch | aarch64
timezone | Europe/Amsterdam

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4747
Installed Version | 1.24.3
Stage | running
Available Repositories | 1012
Downloaded Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 237.7 GB
disk_used | 23.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (4.2.0), Samba share (9.5.1), Log Viewer (0.13.0), SSH & Web Terminal (10.1.1), Samba Backup (5.0.0), Grafana (7.5.2), InfluxDB (4.4.1), Mosquitto broker (6.0.1), Frigate NVR Proxy (1.3), Zigbee2mqtt (1.25.0-1), ESPHome (2022.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 25
views | 8
mode | yaml

</details>

- NetDaemon release with the issue: current
- Last working NetDaemon release (if known): HA core-2022.3
- Operating environment (Home assistant Add-on/Docker/Dev setup): Dev setup

## Link to or paste code that causes the issue
Just run the CodeGenerator project locally on your dev machine connected to your HA instance

**Comment by rcjkierkels** [comment]
This PR should fix the issue:
https://github.com/net-daemon/netdaemon/pull/699

**Comment by rcjkierkels** [comment]
Unfortunality PR #699 has not been merged. Therefor this issue still remains for me.

**Comment by helto4real** [comment]
Ok this is weird we removed the options unless we are missing something

**Comment by FrankBakkerNl** [comment]
Looks like the exact same issue indeed. Make sure you use the latest vetrsion of the codegen.

**Comment by FrankBakkerNl** [comment]
I just double checked, the SelectSelector is really removed from the dev branch since https://github.com/net-daemon/netdaemon/commit/a04ad48bad0d6b47bdbfb7ffb0b3bbe3fd83e3c0 
So I can think of two options:
* You have not merged latest dev branch into your fork
* It is a similar issue with another part of the json that fails to deserialize. If this is the case, can you debug to see exactly what the json is that causes the problem?

**Comment by rcjkierkels** [comment]
Sorry it was my mistake. I was using both a local tool and a global tool and the local was not updated in the tool manifest. So I thought i was using the latest version but was still using the old version. For me tje prtoblem is solved now. Thx!

**Comment by helto4real** [comment]
OK closing this :) Thanks for reporting back.
