### ISSUE TITLE
nd-codegen not working v22.27.0

### ISSUE THREAD

**Issue by filipkauffeldt** [net-daemon/netdaemon#726]
nd-codegen shows this error message after update

Unhandled exception. System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Null'.
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.<ToServicesResult>g__getServiceFields|1_1(String service, JsonElement element, <>c__DisplayClass1_0& ) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/JsonExtensions.cs:line 60
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.<ToServicesResult>g__getServices|1_0(JsonElement element, <>c__DisplayClass1_0& ) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/JsonExtensions.cs:line 40
   at NetDaemon.HassModel.CodeGenerator.Model.JsonExtensions.ToServicesResult(JsonElement element) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Model/JsonExtensions.cs:line 27      
   at Program.<<Main>$>g__GetHaData|0_2(HomeAssistantSettings homeAssistantSettings) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs:line 91
   at Program.<<Main>$>g__GetHaData|0_2(HomeAssistantSettings homeAssistantSettings) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs:line 95
   at Program.<Main>$(String[] args) in /home/runner/work/netdaemon/netdaemon/src/HassModel/NetDaemon.HassModel.CodeGenerator/Program.cs:line 37
   at Program.<Main>(String[] args)

**Comment by helto4real** [comment]
Thank you for reporting the issue. Some questions.
Did you try going back to previous version and generate code. If so what is the latest working version that works for you?
Have you tried restarting HA prior to generate code?
Thanks for your help!

**Comment by filipkauffeldt** [comment]
> 

Last working version was 22.23.0 and the errored occurred after updating  to 22.27.0 without any other known change. After restoring a HA backup with the Netdaemon 22.23.0 and rebooting, codegen still doesn't work.

**Comment by helto4real** [comment]
Please try the 22.27.2 release to see if your problem is fixed. Thanks!

**Comment by helto4real** [comment]
> > 
> 
> Last working version was 22.23.0 and the errored occurred after updating to 22.27.0 without any other known change. After restoring a HA backup with the Netdaemon 22.23.0 and rebooting, codegen still doesn't work.

Can you please try the latest version 22.23.1?

**Comment by filipkauffeldt** [comment]
> > > 
> > 
> > 
> > Last working version was 22.23.0 and the errored occurred after updating to 22.27.0 without any other known change. After restoring a HA backup with the Netdaemon 22.23.0 and rebooting, codegen still doesn't work.
> 
> Can you please try the latest version 22.23.1?

Thank you for addressing the issue so quickly, unfortunately I still get the same issue even after after updating to version 22.27.2 of the home assistant addon and the codegen dotnet tool and rebooting all devices.
