### ISSUE TITLE
Calling dispose twice on DisposableTimer raises a exception

### ISSUE THREAD

**Issue by Barsonax** [net-daemon/netdaemon#798]
## The problem

Calling dispose twice on DisposableTimer raises a exception. According to microsoft documentation a dispose implementation should allow this: https://learn.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?redirectedfrom=MSDN&view=net-7.0#System_IDisposable_Dispose

## Environment

- NetDaemon release with the issue: 22.44.0
- Last working NetDaemon release (if known):
- Operating environment (Home assistant Add-on/Docker/Dev setup): Dev setup
- Link to integration documentation on our website:

## Link to or paste code that causes the issue

```c#
        var timer = new DisposableTimer(CancellationToken.None);
        timer.Dispose();
        timer.Dispose();
```

## Traceback/Error logs

```txt
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at NetDaemon.Extensions.Scheduler.DisposableTimer.Dispose()
```

**Comment by skotl** [comment]
Yep - can confirm that src/Extensions/NetDaemon.Extensions.Scheduling/DisposableTimer.cs doesn't follow the `if (_isDisposed){}` pattern

Do you fancy fixing it and submitting a PR?

**Comment by Barsonax** [comment]
Sure

**Comment by skotl** [comment]
Thanks! "no" would also have been an acceptable answer :D 

Cool - have at it. Are you on Discord, in case you have any issues?

For bonus points, I just checked https://github.com/net-daemon/netdaemon/blob/c12c0c9c15f74c922fd1fb892ab87a557a546ef7/src/Extensions/NetDaemon.Extensions.Scheduling/DisposableScheduler.cs and it doesn't seem to have fully implemented the pattern either.
