### ISSUE TITLE
Could not find a part of the path '/daemon/null' after backup using  Home Assistant Google Drive Backup

### ISSUE THREAD

**Issue by quettih** [net-daemon/netdaemon#833]
## The problem
Using Home Assistant Google Drive Backup you can create your backup and copy them to google drive.
this addon let you stop netdaemon addon, before backing up, and then it can be restarted automatically.
now the problem is on restart: we get the error message

Could not find a part of the path '/daemon/null'  (see log below)

looking around in the code it seems tha working directory changes between stop and start invoked by the backup addon.
if I stop and start manually, it works fine.

## Environment

- NetDaemon release with the issue:  3.1  v 23.5.0
- Last working NetDaemon release (if known): not known
- Operating environment (Home assistant Add-on/Docker/Dev setup):  Home assistant
- Link to integration documentation on our website:

```c#

```

## Traceback/Error logs
[08:48:39] INFO: Starting NetDaemon V3 Runtime ...
Failed to start host... System.IO.DirectoryNotFoundException: **Could not find a part of the path '/daemon/null'**.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at NetDaemon.AppModel.ConfigurationBuilderExtensions.AddYamlAppConfig(IConfigurationBuilder builder, String appConfigPath) in /usr/src/AppModel/NetDaemon.AppModel/Common/Extensions/IConfigurationBuilderExtensions.cs:line 32
   at NetDaemon.Runtime.HostBuilderExtensions.<>c.<UseNetDaemonAppSettings>b__0_1(HostBuilderContext ctx, IConfigurationBuilder config) in /usr/src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs:line 29
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in /usr/src/Host/NetDaemon.Host.Default/Program.cs:line 19
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/daemon/null'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at NetDaemon.AppModel.ConfigurationBuilderExtensions.AddYamlAppConfig(IConfigurationBuilder builder, String appConfigPath) in /usr/src/AppModel/NetDaemon.AppModel/Common/Extensions/IConfigurationBuilderExtensions.cs:line 32
   at NetDaemon.Runtime.HostBuilderExtensions.<>c.<UseNetDaemonAppSettings>b__0_1(HostBuilderContext ctx, IConfigurationBuilder config) in /usr/src/Runtime/NetDaemon.Runtime/Common/Extensions/HostBuilderExtensions.cs:line 29
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in /usr/src/Host/NetDaemon.Host.Default/Program.cs:line 19
   at Program.<Main>(String[] args)
[08:48:47] WARNING: No MQTT add-on installed, MQTT features will not work.

```txt

```

## Additional information
you can install the addon google backup drive, configure backup to stop netdaemon and backup a lot of addons (including database) and schedule it to run (or start manually)

**Comment by helto4real** [comment]
Sorry I do not even begin to know how to figure this one out.

**Comment by helto4real** [comment]
Closing this one. Stale. Please re-open if issue still persist and you can provide more to look for.
